### ISSUE TITLE
cannot use the keymap for goto definition

### ISSUE THREAD

**Issue by bien6mui** [lintingbin2009/sublime_erl#1]
Hi nice author, 

It is a very nice project, it is very helpful for me in the work :))
ButI get one issue about how to use the keymap for goto a definition in Sublime, I see that you already defined a keymao "ctrl+shift+g", but i cannot use it anymore, so please give me the solution for this case. :p 

Thank you so much,
/Bien

**Comment by lintingbin** [comment]
This keymap "ctrl+shift+g" isn't work. I forgot to delete it. If you want to use the goto function, you just move the mouse to the M:F(), then select one option. Like the dynamic demonstration of the readme.

**Comment by bien6mui** [comment]
Thanks for your quick answer, but if possible, adding that keymap into your project, I think it will be so interesting :p

**Comment by lintingbin** [comment]
@bien6mui I have added this function to the latest "1.0.8" version and you can test it in your pc.

**Comment by bien6mui** [comment]
Many thanks @lintingbin2009 , it works well now, :p

it is really a nice project with a nice improvement! :)

**Comment by lintingbin** [comment]
Can you help me star the project. Let more people use it.

**Comment by bien6mui** [comment]
Sure, that is a nice project :p

But I just see one more thing that I think it will be better if you can modify it :p. 
That is with some functions, when we press "ctrl+shift+g" then we will have only one choice for this function. So I think for that case,when we press "ctrl+shift+g" then it will move to this function immediately.

Thanks.

**Comment by lintingbin** [comment]
"No auto selection function" has an advantage that if we don't press the "enter" when we press "ctrl+shift+g" then we can press "esc" to go back quickly. I will think about you advice in the next version.
