### ISSUE TITLE
add "goto_definition" to a defined value (?VALUE) which come from another (.hrl) file

### ISSUE THREAD

**Issue by bien6mui** [lintingbin2009/sublime_erl#3]
hi @lintingbin2009, really sorry because I took too much time from you for some issues and improvements :))
I just see one more thing which maybe makes your project better. :))

Assume that, in our module, we imported some **.hrl** file, for example: **include_lib("file_1.hrl")** or **include("file_2.hrl"**), so we can use the defined value that already defined in two those **.hrl** files in our module. So my idea here is should we add "goto_definition" to goto the defined value (?VALUE) which come from other **.hrl** files

**Comment by lintingbin** [comment]
If you include a .hrl file through relative path or absolute path, then the plugin can show the definition of the macro or record. But if you just include .hrl file through file name, I have no idea to find the path of the .hrl file.

**Comment by bien6mui** [comment]
Let me check it on next Monday in my company,  because I remember that at last time, I cannot use that feature for this case. :))

ahha, may I ask you about your company? I guess that is Ericsson :))

**Comment by lintingbin** [comment]
No, I work in a game company.

**Comment by bien6mui** [comment]
ahha, :)), do you use Erlang in your project? I am working in a small area of Ericsson :)), You know, Erlang stands for **Er**icsson **lang**uage :)

**Comment by lintingbin** [comment]
Yes, we use Erlang to write server code.

**Comment by bien6mui** [comment]
I just checked my source code and I see that:

- With the defined value which is including in a same file, then your plugin can find that value.
- But with the defined value which is including in include header (.hrl), then your plugin cannot find that value. Fortunately,  default Erlang plugin of Sublime can support it :))

So I think if possible, you should make it into your plugin, because your plugin can show that value clearly prettily  :p

pls help me to check it again :))

**Comment by lintingbin** [comment]
It is ok in my PC.
You need include .hrl file through "-include("../arena/arena_record.hrl")." when the .hrl file not in current directory.

**Comment by bien6mui** [comment]
yes, you are right :)), but in my project which already wrote by some guys then it just added "   -include("sbg_st_test_support.hrl").",  not include that full routing directly to hrl file

But your plugin is ok for me now, because it can be used by default Erlang plugin of Sublime plugin

So, you can close the ticket for this issue :))
